
import React, { useState } from 'react';

const sqlScript = `-- CUIDADO: Este script removerá a tabela 'users_north' se ela existir.
-- Faça backup dos dados se necessário antes de executar.
DROP TABLE IF EXISTS public.users_north;

-- Cria a nova tabela 'cleazy_users' para os usuários do serviço.
CREATE TABLE public.cleazy_users (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  username text NOT NULL,
  password text NOT NULL,
  CONSTRAINT cleazy_users_pkey PRIMARY KEY (id),
  CONSTRAINT cleazy_users_username_key UNIQUE (username)
);

-- Habilita a Segurança em Nível de Linha (RLS) para a tabela.
ALTER TABLE public.cleazy_users ENABLE ROW LEVEL SECURITY;

-- Cria políticas de acesso. Esta política permite acesso público total.
-- Para uma aplicação em produção, considere políticas mais restritivas.
CREATE POLICY "Permitir acesso público completo" ON public.cleazy_users FOR ALL
USING (true)
WITH CHECK (true);
`;

interface DatabaseSetupScreenProps {
  onComplete: () => void;
}

export const DatabaseSetupScreen: React.FC<DatabaseSetupScreenProps> = ({ onComplete }) => {
  const [copied, setCopied] = useState(false);
  const [showError, setShowError] = useState(false);

  const copyToClipboard = () => {
    navigator.clipboard.writeText(sqlScript).then(() => {
        setCopied(true);
        setTimeout(() => setCopied(false), 2500);
    }).catch(err => {
        console.error('Falha ao copiar o script:', err);
        setShowError(true);
        setTimeout(() => setShowError(false), 3000);
    });
  };

  return (
    <div className="bg-gray-100 min-h-screen flex flex-col items-center justify-center font-sans p-4">
      <div className="w-full max-w-2xl mx-auto">
        <div className="flex justify-center mb-8">
            <img 
              src="https://raw.githubusercontent.com/riquelima/Cleazy-Clean-Services/refs/heads/main/logo-transparent.png" 
              alt="Cleazy Clean Services Logo"
              className="w-56 h-auto"
            />
        </div>
        <div className="bg-white p-8 rounded-2xl shadow-lg text-center">
            <h1 className="text-2xl font-bold text-gray-900 mb-2">Configuração Necessária</h1>
            <p className="text-gray-600 mb-6 max-w-xl mx-auto">
              A tabela de usuários (<code>cleazy_users</code>) não foi encontrada. Por favor, execute o script SQL abaixo no seu 
              <a 
                href="https://supabase.com/dashboard/project/_/sql" 
                target="_blank" 
                rel="noopener noreferrer" 
                className="text-cyan-600 hover:underline font-medium"
              >
                {' '}Editor de SQL do Supabase{' '}
              </a> 
              para criar e configurar a tabela.
            </p>

            <div className="bg-gray-800 p-4 pt-12 rounded-lg text-left relative shadow-lg">
              <pre className="text-sm text-gray-200 whitespace-pre-wrap overflow-auto max-h-60">
                <code>{sqlScript}</code>
              </pre>
              <button 
                onClick={copyToClipboard}
                className="absolute top-3 right-3 bg-gray-600 hover:bg-gray-500 text-white font-semibold py-1.5 px-4 rounded-md text-xs transition-colors focus:outline-none focus:ring-2 focus:ring-cyan-500"
              >
                {copied ? 'Copiado!' : 'Copiar Script'}
              </button>
            </div>
            
            {showError && <p className="text-red-500 mt-4 text-sm">Não foi possível copiar. Por favor, copie o texto manualmente.</p>}

            <button
              onClick={onComplete}
              className="w-full max-w-sm mt-8 p-3 rounded-lg text-white font-semibold bg-cyan-500 hover:bg-cyan-600 transition-all transform hover:scale-105 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-white focus:ring-cyan-500"
            >
              Já executei o script. Continuar
            </button>
        </div>
      </div>
    </div>
  );
};